import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, 'data', 'counseling.db')
SECRET_KEY = 'campus-counseling-secret-key-2024'
SESSION_COOKIE_NAME = 'cc_session'
CHECKIN_WINDOW_MINUTES_BEFORE = 15
CHECKIN_WINDOW_MINUTES_AFTER = 30
NO_SHOW_THRESHOLD = 3
COOLDOWN_DAYS = 7

RISK_LEVEL_HIGH_THRESHOLD = 3
RISK_LEVEL_MEDIUM_THRESHOLD = 2
ABNORMAL_BOOKING_DAILY_LIMIT = 3
ABNORMAL_BOOKING_WEEKLY_LIMIT = 8
ABNORMAL_CANCEL_RATE_THRESHOLD = 0.4

CHECKIN_REMINDER_MINUTES_BEFORE = 10
CHECKIN_ANOMALY_LATE_MINUTES = 15

ROOM_UTILIZATION_HOURS_PER_DAY = 8
